[package]
name = "YJ_201125"
version = "0.1.0"
authors = ["yeee-z6 <adam99117@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.4.0"